ETicaret.WebUI/Areas/Admin/Controllers/BrandsController.cs
using ETicaret.Entities;
using ETicaret.Service.Abstract;
using ETicaret.WebUI.Areas.Admin.Models;
using ETicaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.WebUI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandsController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        // GET: BrandsController
        public ActionResult Index()
        {
            var marka = new BrandListModel()
            {
                Brands = _brandService.GetAll()
            };
            return View(marka);
        }

        // GET: BrandsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BrandsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BrandsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(BrandModel brand, IFormFile? Logo, string filePath = "/Img/Brands/")
        {
            if (ModelState.IsValid)
            {
                try
                {
                    brand.Logo = await FileHelper.FileLoaderAsync(Logo, filePath);
                    var marka = new Brand()
                    {
                        Name = brand.Name,
                        Description = brand.Description,
                        Logo = brand.Logo,
                        IsActive = brand.IsActive,
                        CreateDate = DateTime.Now,
                    };
                    await _brandService.AddAsync(marka);
                    await _brandService.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }
            return View(brand);
        }


        // POST: BrandsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create2(Brand brand, IFormFile? Logo)
        {
            if (ModelState.IsValid) // Model class ımız olan brand nesnesinin validasyon için koyduğumuz kurallarınıa (örneğin marka adı required-boş geçilemez gibi) uyulmuşsa
            {
                try
                {
                    brand.Logo = await FileHelper.FileLoaderAsync(Logo);
                    _brandService.Add(brand);
                    _brandService.SaveChanges();
                    return RedirectToAction("Create", "Products");
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }

            return View(brand);
        }

        // GET: BrandsController/Edit/5
        public async Task<ActionResult> EditAsync(int id)
        {
            var model = await _brandService.FindAsync(id);
            var marka = new BrandModel()
            {
                Id = model.Id,
                Name = model.Name,
                Description= model.Description,
                Logo = model.Logo,
                IsActive = model.IsActive,
                CreateDate = DateTime.Now
            };
            return View(marka);
        }

        // POST: BrandsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, BrandModel brands, IFormFile? Logo, string filePath = "/Img/Brands/")
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Logo is not null) brands.Logo = await FileHelper.FileLoaderAsync(Logo, filePath);
                    var model = new Brand()
                    {
                        Id = brands.Id,
                        Name = brands.Name,
                        Description = brands.Description,
                        Logo = brands.Logo,
                        IsActive = brands.IsActive,
                        CreateDate = DateTime.Now
                    };
                    _brandService.Update(model);
                    await _brandService.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }
            return View(brands);
        }

        // GET: BrandsController/Delete/5
        public async Task<ActionResult> DeleteAsync(int id)
        {
            var model = await _brandService.FindAsync(id);
            var marka = new BrandModel()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Logo = model.Logo,
                IsActive = model.IsActive,
                CreateDate = DateTime.Now
            };
            return View(marka);
        }

        // POST: BrandsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(int id, Brand brands, string filePath = "/Img/Brands/")
        {
            try
            {
                FileHelper.FileRemover(brands.Logo, filePath);
                _brandService.Delete(brands);
                await _brandService.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ETicaret.WebUI/Areas/Admin/Controllers/ProductsController.cs
using ETicaret.Entities;
using ETicaret.Service.Abstract;
using ETicaret.WebUI.Areas.Admin.Models;
using ETicaret.WebUI.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ETicaret.WebUI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IBrandService _brandService;
        private readonly ICategoryService _categoryService;
        
        public ProductsController(IProductService productService, IBrandService brandService, ICategoryService categoryService)
        {
            _productService = productService;
            _brandService = brandService;
            _categoryService = categoryService;
        }
        // GET: ProductsController
        public ActionResult Index()
        {
            var urun = new ProductListModel()
            {
                Products = _productService.GetAll()
            };
            return View(urun);
        }

        // GET: ProductsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductsController/Create
        public async Task<ActionResult> CreateAsync()
        {
            ViewBag.CategoryId = new SelectList(await _categoryService.GetAllAsync(), "Id", "Name");
            ViewBag.BrandId = new SelectList(await _brandService.GetAllAsync(), "Id", "Name");
            return View();
        }

        // POST: ProductsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAsync(ProductModel product, IFormFile? Image, string filePath = "/Img/Products/")
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (Image is not null) product.Image = await FileHelper.FileLoaderAsync(Image, filePath);
                    var urun = new Product()
                    {
                        Name = product.Name,
                        Description= product.Description,
                        Image= product.Image,
                        CreateDate = DateTime.Now,
                        UpdateDate = DateTime.Now,
                        IsActive = product.IsActive,
                        IsHome= product.IsHome,
                        Price = product.Price,
                        Stock = product.Stock,
                        CategoryId = product.CategoryId,
                        BrandId = product.BrandId
                    };
                    await _productService.AddAsync(urun);
                    await _productService.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }
            return View(product);
        }

        // GET: ProductsController/Edit/5
        public async Task<ActionResult> EditAsync(int id)
        {
            var model = await _productService.FindAsync(id);
            var urun = new ProductModel()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Image = model.Image,
                CreateDate = DateTime.Now,
                UpdateDate = DateTime.Now,
                IsActive = model.IsActive,
                IsHome = model.IsHome,
                Price = model.Price,
                Stock = model.Stock,
                CategoryId = model.CategoryId,
                BrandId = model.BrandId
            };
            ViewBag.CategoryId = new SelectList(await _categoryService.GetAllAsync(), "Id", "Name");
            ViewBag.BrandId = new SelectList(await _brandService.GetAllAsync(), "Id", "Name");
            return View(urun);
        }

        // POST: ProductsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, ProductModel product, IFormFile? Image, bool? resmisil, string filePath = "/Img/Products/" )
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (resmisil == true)
                    {
                        FileHelper.FileRemover(product.Image, filePath);
                        product.Image = string.Empty;
                    }
                    if (Image is not null)
                    {
                        FileHelper.FileRemover(product.Image, filePath);
                        product.Image = await FileHelper.FileLoaderAsync(Image, filePath);
                    }
                    var urun = new Product()
                    {
                        Id = product.Id,
                        Name = product.Name,
                        Description = product.Description,
                        Image = product.Image,
                        CreateDate = DateTime.Now,
                        UpdateDate = DateTime.Now,
                        IsActive = product.IsActive,
                        IsHome = product.IsHome,
                        Price = product.Price,
                        Stock = product.Stock,
                        CategoryId = product.CategoryId,
                        BrandId = product.BrandId
                    };
                    _productService.Update(urun);
                    await _productService.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    ModelState.AddModelError("", "Hata Oluştu!");
                }
            }
            return View(product);
        }

        // GET: ProductsController/Delete/5
        public async Task<ActionResult> DeleteAsync(int id)
        {
            var model = await _productService.FindAsync(id);
            var urun = new ProductModel()
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Image = model.Image,
                CreateDate = DateTime.Now,
                UpdateDate = DateTime.Now,
                IsActive = model.IsActive,
                IsHome = model.IsHome,
                Price = model.Price,
                Stock = model.Stock,
                CategoryId = model.CategoryId,
                Category = model.Category,
                BrandId = model.BrandId,
                Brand = model.Brand
            };
            ViewBag.CategoryId = new SelectList(await _categoryService.GetAllAsync(), "Id", "Name");
            ViewBag.BrandId = new SelectList(await _brandService.GetAllAsync(), "Id", "Name");
            return View(urun);
        }

        // POST: ProductsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(int id, Product product, string filePath = "/Img/Products/")
        {
            try
            {
                FileHelper.FileRemover(product.Image, filePath);
                _productService.Delete(product);
                await _productService.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ETicaret.WebUI/Controllers/BrandsController.cs
using ETicaret.Service.Abstract;
using ETicaret.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.WebUI.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly IProductService _productService;
        public BrandsController(IBrandService brandService, IProductService productService)
        {
            _brandService = brandService;
            _productService = productService;
        }
        public async Task<IActionResult> IndexAsync(int id)
        {
            var model = new BrandPageViewModel()
            {
                Brand = await _brandService.FindAsync(id),
                Products = await _productService.GetAllAsync(p => p.IsActive && p.BrandId == id)
            };
            return View(model);
        }
    }
}

ETicaret.WebUI/Controllers/CategoriesController.cs
using ETicaret.Service.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.WebUI.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var model = await _categoryService.GetCategoryByProductsAsync(id);
            return View(model);
        }
    }
}

ETicaret.WebUI/Controllers/ProductsController.cs
using ETicaret.Service.Abstract;
using ETicaret.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETicaret.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Search(string q)
        {
            var urun = await _productService.GetAllAsync(p => p.IsActive && p.Name.Contains(q));
            var model = new SearchModel()
            {
                search = q,
                Products = urun
            };
            return View(model);
        }

        public async Task<ActionResult> DetailAsync(int id)
        {
            var product = await _productService.GetProductByCategoriesBrandsAsync(id);
            var model = new ProductDetailViewModel()
            {
                Product = product,
                Products = await _productService.GetAllAsync(p => p.IsActive && p.Id != id)
            };

            return View(model);
        }
    }
}

ETicaret.WebUI/Views/Shared/_Brands.cshtml
@model IEnumerable<Brand>
@{
}
<!-- Vendor Start -->
<div class="container-fluid py-5">
    <div class="row px-xl-5">
        <div class="col">
            <div class="owl-carousel vendor-carousel">
                @foreach (var item in Model)
                {
                    <a asp-controller="Brands" asp-action="Index" asp-route-id="@item.Id">
                        <img src="/Img/Brands/@item.Logo" alt="@item.Name" title="@item.Name" style="width:70px; height:60px"/>
                    </a>
                }
            </div>
        </div>
    </div>
</div>
<!-- Vendor End -->

ETicaret.WebUI/Views/Shared/_Categories.cshtml
@model IEnumerable<Category>
@{
}
<!-- Categories Start -->
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Kategoriler</span></h2>
    <div class="row px-xl-5 pb-3">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <a asp-controller="Categories" asp-action="Index" asp-route-id="@item.Id" class="text-decoration-none">
                    <div class="cat-item d-flex align-items-center mb-4">
                        <div class="overflow-hidden pt-4" style="max-width: 150px; height: 150px;">
                            <img class="img-fluid" src="/Img/Categories/@item.Image" alt="@item.Name" title="@item.Name">
                        </div>
                        <div class="flex-fill pl-3">
                            <h6>@item.Name</h6>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>
<!-- Categories End -->

ETicaret.WebUI/Views/Shared/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Bize Ulaşın</h5>
            <div class="d-flex flex-column justify-content-start">
                <a class="text-secondary mb-2" href="/BizKimiz"><i class="fa fa-angle-right mr-2"></i>Biz Kimiz</a>
                <a class="text-secondary mb-2" href="/"><i class="fa fa-angle-right mr-2"></i>Ana Sayfa</a>
                <a class="text-secondary mb-2" href="/iletisim"><i class="fa fa-angle-right mr-2"></i>İletişim</a>
            </div>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Caddesi, Kışım Sokak, Kadıköy İSTANBUL</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i><a href="mailto:info@example.com">info@example.com</a></p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+0212 212 1212</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">MARKALAR</h5>
                    <div class="d-flex flex-column justify-content-start">
                        @await Component.InvokeAsync("Brands")
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">KATEGORİLER</h5>
                    <div class="d-flex flex-column justify-content-start">
                        @await Component.InvokeAsync("Categories1")
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">BÜLTEN</h5>
                    <p>Kampanyaları kaçırmamak için takipte kalın</p>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Email">
                            <div class="input-group-append">
                                <button class="btn btn-primary">Giriş Yap</button>
                            </div>
                        </div>
                    </form>
                    <h6 class="text-secondary text-uppercase mt-4 mb-3">Sosyal Medya</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Tüm Haklar Saklıdır</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="/onyuzsayfa/img/payments.png" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

ETicaret.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETicaret.WebUI</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="/onyuzsayfa/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/onyuzsayfa/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/onyuzsayfa/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/onyuzsayfa/css/style.css" rel="stylesheet">
</head>
<body>
    <partial name="_TopBar"/>

    <partial name="_NavBar" />

    <div class="">
        <main role="main" class="pb-3">
            @if (TempData["message"] != null)
            {
                <partial name="_ResultMessage" model="@(TempData.Get<AlertMessage>("message"))" />
            }

            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="/onyuzsayfa/lib/easing/easing.min.js"></script>
    <script src="/onyuzsayfa/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="/onyuzsayfa/mail/jqBootstrapValidation.min.js"></script>
    <script src="/onyuzsayfa/mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="/onyuzsayfa/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ETicaret.WebUI/Views/Shared/_NavBar.cshtml
 <!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Kategoriler</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    <div class="nav-item dropdown dropright">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Giyim <i class="fa fa-angle-right float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                            <a href="" class="dropdown-item">Erkek Giyim</a>
                            <a href="" class="dropdown-item">Kadın Giyim</a>
                            <a href="" class="dropdown-item">Bebek Giyim</a>
                        </div>
                    </div>
                    <a href="" class="nav-item nav-link">Gömlek</a>
                    <a href="" class="nav-item nav-link">Kot</a>
                    <a href="" class="nav-item nav-link">Mayo</a>
                    <a href="" class="nav-item nav-link">Pijama</a>
                    <a href="" class="nav-item nav-link">Spor giyim</a>
                    <a href="" class="nav-item nav-link">Tulum</a>
                    <a href="" class="nav-item nav-link">Blazer</a>
                    <a href="" class="nav-item nav-link">Ceket</a>
                    <a href="" class="nav-item nav-link">Ayakkabı</a>
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="/" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Sarı</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Kedi</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="/" class="nav-item nav-link active">Anasayfa</a>
                        @await Component.InvokeAsync("Categories")
                        <a href="/iletisim" class="nav-item nav-link">İletişim</a>
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a href="/Cart" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">Sepetim</span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->

ETicaret.WebUI/Views/Shared/_Products.cshtml
@model IEnumerable<Product>
@{
}
<!-- Products Start -->
@foreach (var item in Model)
{
    <div class="product-item bg-light mb-4">
        <div class="product-img position-relative overflow-hidden">
            <img class="img-fluid w-100" src="/Img/Products/@item.Image" alt="@item.Name" title="@item.Name">
            @{
                if (User.Identity.IsAuthenticated)
                {
                    <div class="product-action">
                        <a class="btn btn-outline-dark btn-square" href="/Cart/AddToCart"><i class="fa fa-shopping-cart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="#"><i class="far fa-heart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="#"><i class="fa fa-sync-alt"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="/Products/Search"><i class="fa fa-search"></i></a>
                    </div>
                }
                else
                {
                    <div class="product-action">
                        <a class="btn btn-outline-dark btn-square" href="/Account/Login"><i class="fa fa-shopping-cart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="/Account/Login"><i class="far fa-heart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="/Account/Login"><i class="fa fa-sync-alt"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="/Account/Login"><i class="fa fa-search"></i></a>
                    </div>
                }
            }
        </div>
        <div class="text-center py-4">
            <a class="h6 text-decoration-none text-truncate" href="/Products/Detail/@item.Id">@item.Name</a>
            <div class="d-flex align-items-center justify-content-center mt-2">
                <h5>@item.Price ₺</h5><h6 class="text-muted ml-2"><del>@item.Price ₺</del></h6>
            </div>
            <div class="d-flex align-items-center justify-content-center mb-1">
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small class="fa fa-star text-primary mr-1"></small>
                <small>(99)</small>
            </div>
        </div>
    </div>
}
<!-- Products End -->

ETicaret.WebUI/Views/Shared/_ResultMessage.cshtml
@model AlertMessage

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-@Model.AlertType">
            <h4 class="alert-title">@Model.Title</h4>
            <p>@Model.Message</p>
        </div>
    </div>
</div>